# Generated by Django 5.0.3 on 2024-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
