# Generated by Django 5.0.3 on 2024-03-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0002_alter_customuser_groups_and_more'),
        ('hrweb', '0003_alter_vacancy_options_alter_vacancy_area_and_more'),
    ]

    operations = [
    ]
