# Generated by Django 5.0.2 on 2024-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0004_merge_20240318_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
