# Generated by Django 5.0.3 on 2024-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0004_merge_20240319_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='График работы'),
        ),
    ]
