# Generated by Django 5.0.2 on 2024-03-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0005_remove_customuser_is_admin_customuser_avatar'),
        ('hrweb', '0005_vacancy_schedule'),
    ]

    operations = [
    ]
