# Generated by Django 5.0.3 on 2024-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0006_merge_20240319_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(default=None, max_length=50, verbose_name='Зарплата max'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(default=None, max_length=50, verbose_name='Зарплата min'),
        ),
    ]
