# Generated by Django 5.0.3 on 2024-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0007_remove_vacancy_salary_vacancy_salary_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(default=0, verbose_name='Зарплата max'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(default=0, verbose_name='Зарплата min'),
        ),
    ]
