# Generated by Django 5.0.3 on 2024-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0008_alter_vacancy_salary_max_alter_vacancy_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.CharField(default=None, max_length=100, verbose_name='Зарплата max'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.CharField(default=None, max_length=100, verbose_name='Зарплата min'),
        ),
    ]
