# Generated by Django 5.0.3 on 2024-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrweb', '0011_alter_vacancy_salary_max_alter_vacancy_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='role',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='Роль'),
        ),
    ]
